// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjo6Qwl6Brm_209Wvq091jbgpNJIKtvoU',
    appId: '1:165533149476:web:1b9bda4746af4a865debb1',
    messagingSenderId: '165533149476',
    projectId: 'sign-2cc4c',
    authDomain: 'sign-2cc4c.firebaseapp.com',
    storageBucket: 'sign-2cc4c.appspot.com',
    measurementId: 'G-8YS96P16HS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCl4ZL_zX7Qm3tMxBqeiPjzQSC8NtgeN_k',
    appId: '1:165533149476:android:407dc00a62eee0e65debb1',
    messagingSenderId: '165533149476',
    projectId: 'sign-2cc4c',
    storageBucket: 'sign-2cc4c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRnA4mNVePNO-J80pKIR0RbH3YpGACja0',
    appId: '1:165533149476:ios:f967055d446cd5725debb1',
    messagingSenderId: '165533149476',
    projectId: 'sign-2cc4c',
    storageBucket: 'sign-2cc4c.appspot.com',
    iosClientId: '165533149476-q0kh444pmf996lghhb3na5vskbg6npd6.apps.googleusercontent.com',
    iosBundleId: 'com.example.authapp',
  );
}
